### PR TITLE
upgrade deps to polkadot-v0.9.24

### PR DESCRIPTION
**Pull request by xcaptain**
1. Cherry-pick changes from insipx/modified-frame-metadata branch
2. upgrade deps

### CODE REVIEW

**Comment by jsdw** [comment]
One thing that needs doing is to also change the serialziation/deserialization to work with BitVec 1.0 in `desub-current`; as it stands, there will be silent errors at the moment when trying to work with anything involving a bitvec.

Personally my approach here would be to make use of the `scale-value` crate in desub-common, which we maintain more actively and does support the latest dependencies afaik (including bitvec 1.0). (see https://github.com/paritytech/scale-value)

`scale-value` drew heavily from my work in `desub-current`, and so making use of it is probably easier than re-implementing the serialization/deserialization stuff :)

**Comment by jsdw** [comment]
Also see https://github.com/paritytech/desub/pull/86 which was a PR with the same goals in mind and also needs this update to avoid bitvec issues.

**Comment by xcaptain** [comment]
I'm not familiar with `scale-value` now, but this branch works for my substrate-archive fork, extrinsics decoding works well(maybe it's because I didn't encounter any bitvec types). I think you can consider merge this pr first, and in the future I can try to integrate `scale-value`.

**Comment by jsdw** [comment]
My suggestion for now would be to continue with your own fork; this project sees very little love at the moment as its primary use case internally was for substrate-archive, which is no longer maintained.

Parts of this project are being extracted and integrated elsewhere though, so over time more of the functionality from here might become available in projetcs like Subxt for instance (though it might take a while for pre-V14 support to arrive there).

**Comment by xcaptain** [comment]
OK, I will close this pull request

**Pull request closed without merging**
