### PR TITLE
Better macro for test.

### PR DESCRIPTION
**Pull request by kianenigma**
I was looking into the code a bit and decided to fix this `TODO`. 

I am looking more into using desub and eventually contributing back. Pointing me out to further small issues could potentially end up in them being resolved by me. 

Only substantial change of this PR is that aside from hardcoding the number of transactions in each block, we use the count of files with a certain prefix (which I am not sure why it wasn't like this from the get go? maybe I am missing a reason here.)

### CODE REVIEW

**Review by dvdplm — APPROVED** [review]
Thanks! Seems like a good cleanup to me, but let's hear from @insipx

**Comment by insipx** [comment]
looks great! TIL about the `paste` macro

**Review by insipx — APPROVED** [review]

**Comment by dvdplm** [comment]
@insipx the CI seems angry for the wrong reasons. Do you know how to kick it in the balls?

**Comment by insipx** [comment]
@dvdplm I have no idea 😅 i've never had CLA crap out before.  Merge is greyed out for me -- maybe we need an admin to push it through?

**Comment by kianenigma** [comment]
I'm not sure what the CI issues other than CLA are about. Anything that I can do per se?

**Comment by dvdplm** [comment]
It looks like the substrate revision is too old to build with nightly rust.

**Comment by insipx** [comment]
#32 fixes most of them, and then it's a matter of figuring out what broke with master on #33 to get it to compile with nightly I think

**Comment by kianenigma** [comment]
merged with master, hopefully can merge now.

**Pull request merged**
